### ISSUE TITLE
Iterator null object reference. Map.java:170

### ISSUE THREAD

**Issue by kruseshane** [Timaden/LabSkele#1]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.labskeletest, PID: 4652
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.lang.Iterable.iterator()' on a null object reference
        at com.google.android.gms.maps.model.PolylineOptions.addAll(Unknown Source:0)
        at com.example.labskeletest.Map$1$1.onLocationChanged(Map.java:170)
        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:371)
        at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:300)
        at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:316)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by kruseshane** [comment]
Issue fixed.
